from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='DeliveryPoint', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=255)),('code',models.CharField(blank=True,max_length=100)),('address',models.CharField(max_length=500)),('kind',models.CharField(choices=[('cmd','CMD'),('invitro','ИНВИТРО'),('external','Сторонняя лаборатория'),('service','Служебная точка'),('unknown','Не определено')],default='unknown',max_length=20)),('phone',models.CharField(blank=True,max_length=64)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))], options={'ordering':('kind','name')}),
        migrations.AddConstraint(model_name='deliverypoint', constraint=models.UniqueConstraint(fields=('code','address'),name='unique_point_code_address')),
        migrations.CreateModel(name='Delivery', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('delivery_date',models.DateField()),('source_label',models.CharField(blank=True,help_text='Исходное значение левой колонки',max_length=255)),('address',models.CharField(max_length=500)),('organization',models.CharField(blank=True,max_length=255)),('recipient',models.CharField(blank=True,max_length=255)),('phone',models.CharField(blank=True,max_length=64)),('comment',models.TextField(blank=True)),('time_window',models.CharField(blank=True,max_length=64)),('row_color',models.CharField(blank=True,choices=[('','Без цвета'),('green','Зелёный'),('yellow','Жёлтый'),('red','Красный'),('blue','Синий'),('gray','Серый')],default='',max_length=16)),('route_order',models.PositiveIntegerField(default=0)),('status',models.CharField(choices=[('new','Новая'),('in_progress','В работе'),('done','Выполнена'),('problem','Проблема')],default='new',max_length=20)),('problem_reason',models.CharField(blank=True,max_length=255)),('completed_at',models.DateTimeField(blank=True,null=True)),('completed_latitude',models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),('completed_longitude',models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('courier',models.ForeignKey(blank=True,limit_choices_to={'role':'courier'},null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='deliveries',to=settings.AUTH_USER_MODEL)),('point',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='deliveries',to='deliveries.deliverypoint'))], options={'ordering':('delivery_date','courier_id','route_order','id')}),
        migrations.CreateModel(name='DeliveryEvent', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=64)),('note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('delivery',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='events',to='deliveries.delivery'))]),
    ]
