from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('deliveries','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='Route',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True)),('is_active',models.BooleanField(default=True)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('default_courier',models.ForeignKey(blank=True,limit_choices_to={'role':'courier'},null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='default_routes',to=settings.AUTH_USER_MODEL))],options={'ordering':('name',)}),
        migrations.CreateModel(name='RouteTemplate',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('kind',models.CharField(choices=[('weekday','Будни'),('weekend','Выходные'),('custom','Особый')],max_length=20)),('name',models.CharField(blank=True,max_length=120)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('route',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='templates',to='deliveries.route'))],options={'ordering':('route__name','kind','name')}),
        migrations.AddConstraint(model_name='routetemplate',constraint=models.UniqueConstraint(fields=('route','kind','name'),name='unique_route_template_variant')),
        migrations.CreateModel(name='RouteTemplateItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('route_order',models.PositiveIntegerField(default=0)),('enabled_by_default',models.BooleanField(default=True)),('time_window',models.CharField(blank=True,max_length=64)),('comment',models.CharField(blank=True,max_length=255)),('point',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='route_template_items',to='deliveries.deliverypoint')),('template',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='deliveries.routetemplate'))],options={'ordering':('route_order','id')}),
        migrations.AddConstraint(model_name='routetemplateitem',constraint=models.UniqueConstraint(fields=('template','point'),name='unique_point_per_route_template')),
        migrations.CreateModel(name='RouteRun',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('run_date',models.DateField()),('status',models.CharField(choices=[('draft','Черновик'),('ready','Готов'),('in_progress','В работе'),('done','Завершён')],default='draft',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('assigned_courier',models.ForeignKey(blank=True,limit_choices_to={'role':'courier'},null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='route_runs',to=settings.AUTH_USER_MODEL)),('route',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='runs',to='deliveries.route')),('template',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='runs',to='deliveries.routetemplate'))],options={'ordering':('-run_date','route__name')}),
        migrations.AddConstraint(model_name='routerun',constraint=models.UniqueConstraint(fields=('route','run_date'),name='unique_route_run_per_day')),
        migrations.AddField(model_name='delivery',name='route_run',field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='deliveries',to='deliveries.routerun')),
    ]
